# Generated by Django 6.0.3 on 2026-03-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('notified', 'Eslatildi'), ('done', 'Bajarildi')], default='pending', max_length=10),
        ),
    ]
